[workspace]
authors = ["Mtrya <erchanmion20@outlook.com>"]
channels = ["conda-forge", "tudat-team"]
name = "astro-reason"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.12.12,<3.13"
pip = ">=26.0.1,<27"
bubblewrap = ">=0.11.0,<0.12"
pytest = ">=9.0.2,<10"

[pypi-dependencies]
requests = ">=2.32.5, <3"
skyfield = ">=1.54, <2"
numpy = ">=2.4.2, <3"
brahe = ">=1.0.1, <2"
